gui:
  skipAmendWarning: true
  skipStashWarning: true
  nerdFontsVersion: 3
git:
  branchPrefix: "subham/"
notARepository: skip
customCommands:
  - key: '<c-p>'
    context: 'localBranches'
    command: 'git push origin {{.SelectedLocalBranch.Name}}'
    description: 'Push selected branch to origin'
