[general]
import = [
"~/.config/alacritty/themes/gruvbox.toml",
]
[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[font]
offset = {x = 1, y = 1}

[scrolling]
history = 10000

[window]
opacity = 0.9
startup_mode = "Maximized"
decorations = "none"
option_as_alt = "Both"

[mouse]
hide_when_typing = true
